languages: ["en-EN", "ru-RU", "de-DE"]
canvas_width: 6144
canvas_height: 2732

layer0:
  image: "fastlane/actions/merge_screenshots/assets/iPadProBg.png"

layer1:
  image: 
    en-EN: "screenshots/dark/en-EN/iPad Pro (12.9-inch) (4th generation)-03Library.png"
    ru-RU: "screenshots/dark/ru-RU/iPad Pro (12.9-inch) (4th generation)-03Library.png"
    de-DE: "screenshots/dark/de-DE/iPad Pro (12.9-inch) (4th generation)-03Library.png"
  position:
    x: 4301
    y: 288
  size:
    width: 1641
    height: 2156

layer2:
  image:
    en-EN: "screenshots/light/en-EN/iPad Pro (12.9-inch) (4th generation)-02FileList.png"
    ru-RU: "screenshots/light/ru-RU/iPad Pro (12.9-inch) (4th generation)-02FileList.png"
    de-DE: "screenshots/light/de-DE/iPad Pro (12.9-inch) (4th generation)-02FileList.png"
  position:
    x: 2253
    y: 288
  size:
    width: 1641
    height: 2156

layer3:
  image: "fastlane/actions/merge_screenshots/assets/iPad3Generation.png"
  position:
    x: 91
    y: 830
  shadow:
    sigma: 20
    dx: 20
    dy: 20
    alpha: 0.3

layer4:
  image:
    en-EN: "screenshots/dark/en-EN/iPad Pro (12.9-inch) (4th generation)-01BookList.png"
    ru-RU: "screenshots/dark/ru-RU/iPad Pro (12.9-inch) (4th generation)-01BookList.png"
    de-DE: "screenshots/dark/de-DE/iPad Pro (12.9-inch) (4th generation)-01BookList.png"
  position:
    x: 193
    y: 1050

layer5:
  image: "fastlane/actions/merge_screenshots/assets/iPad4Generation.png"
  position:
    x: 367
    y: 1654
  shadow:
    sigma: 20
    dx: 20
    dy: 20
    alpha: 0.3

layer6:
  image:
    en-EN: "screenshots/light/en-EN/iPad Pro (12.9-inch) (4th generation)-01BookList.png"
    ru-RU: "screenshots/light/ru-RU/iPad Pro (12.9-inch) (4th generation)-01BookList.png"
    de-DE: "screenshots/light/de-DE/iPad Pro (12.9-inch) (4th generation)-01BookList.png"
  position:
    x: 464
    y: 1757

layer7:
  text:
    en-EN: "Offline mp3-player for listening to\naudiobooks, lectures, music"
    ru-RU: "Оффлайн mp3-плеер для\nаудиокниг, лекций, музыки"
    de-DE: "Offline-MP3-Player zum Anhören\nvon Hörbüchern, Vorträgen und Musik"
  font: "PlayfairDisplay Medium 100"
  fontfile: "fastlane/actions/merge_screenshots/font/PlayfairDisplay-Medium.ttf"
  align: "centre" #centre or low or high
  color: 0x42303c
  position:
    x: 0
    y: 100
  width: 2048

layer8:
  text: 
    en-EN: "+ Free and without ads\n+ Bookmarks\n+ Dark theme"
    ru-RU: "+ Бесплатно, без рекламы\n+ Закладки\n+ Тёмная тема"
    de-DE: "+ Kostenlos, ohne Werbung\n+ Lesezeichen\n+ Dark Mode"
  font: "PlayfairDisplay Medium 80"
  fontfile: "fastlane/actions/merge_screenshots/font/PlayfairDisplay-Medium.ttf"
  align: "low" #centre or low or high
  color: 0x42303c
  position:
    x: 90
    y: 410
  width: 1800

output:
  frame: 2048
  en-EN: ["screenshots/en-EN/iPadPro/01BookList.png", "screenshots/en-EN/iPadPro/02FileList.png", "screenshots/en-EN/iPadPro/03Library.png"]
  ru-RU: ["screenshots/ru-RU/iPadPro/01BookList.png", "screenshots/ru-RU/iPadPro/02FileList.png", "screenshots/ru-RU/iPadPro/03Library.png"]
  de-DE: ["screenshots/de-DE/iPadPro/01BookList.png", "screenshots/de-DE/iPadPro/02FileList.png", "screenshots/de-DE/iPadPro/03Library.png"]




